spring:
  profiles:
    active: ${APP_PROFILE:test}

---
spring:
  config:
    activate:
      on-profile: "test"

  datasource:
    url: jdbc:postgresql://localhost:5433/propostadb
    username: postgres
    password: 1234567

  jpa:
    hibernate:
      show-sql: true
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect