spring:
  profiles:
    active: ${APP_PROFILE:test}

rabbitmq:
  pendingproposal:
    exchange: proposta-pedente.ex

---
spring:
  config:
    activate:
      on-profile: "test"

  datasource:
    url: jdbc:postgresql://localhost:5433/propostadb
    username: postgres
    password: 1234567

    rabbitmq:
      host: localhost
      port: 5672
      username: guest
      password: guest

  jpa:
    hibernate:
      show-sql: true
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect